-- Create Article table
CREATE TABLE Article (
  Id SERIAL PRIMARY KEY,
  Title VARCHAR(50) NOT NULL,
  Content VARCHAR(500) NOT NULL,
  CreatedAt TIMESTAMP NOT NULL DEFAULT NOW(),
  UpdatedAt TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Create Tag table
CREATE TABLE Tag (
  Id SERIAL PRIMARY KEY,
  Name VARCHAR(50) NOT NULL,
  CreatedAt TIMESTAMP NOT NULL DEFAULT NOW(),
  UpdatedAt TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Create ArticleTag table to establish the many-to-many relationship
CREATE TABLE ArticleTag (
  ArticleId INTEGER NOT NULL REFERENCES Article(Id) ON DELETE CASCADE,
  TagId INTEGER NOT NULL REFERENCES Tag(Id) ON DELETE CASCADE,
  CreatedAt TIMESTAMP NOT NULL DEFAULT NOW(),
  UpdatedAt TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (ArticleId, TagId)
);
